### ISSUE TITLE
MGRS code is throwing an exception

### ISSUE THREAD

**Issue by empbarney** [missioncommand/emp3-android#104]
This has the code from development branch: pulled on March 27th 2017
commit e97eecdbfd4fd022370eaec23c3dbfc754c502da

03-27 12:19:34.358 13031-13237/mil.emp3.test.emp3vv I/BoundsGenerationTest: Pos String -136.6236042301427,-12.205443146957585,-16.623604230142703,90.0
03-27 12:19:34.358 13031-13237/mil.emp3.test.emp3vv E/BoundsGenerationTest: fetchPositionsFromString not enough pairs 1
03-27 12:19:34.368 13031-13031/mil.emp3.test.emp3vv D/AndroidRuntime: Shutting down VM
03-27 12:19:34.378 13031-13031/mil.emp3.test.emp3vv E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: mil.emp3.test.emp3vv, PID: 13031
                                                                      java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Point.x' on a null object reference
                                                                          at mil.emp3.core.mapgridlines.AbstractMapGridLine$1.run(AbstractMapGridLine.java:236)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
03-27 12:19:34.378 4304-9607/? W/ActivityManager:   Force finishing activity mil.emp3.test.emp3vv/.ValidateAndVerify

**Comment by Ish-rivera** [comment]
This has been corrected.
